export const UPDATE_PILLS = "UPDATE_PILLS";

export const ADD_TO_COUNT = "ADD_TO_COUNT";
export const ADD_MULTIPLE_TO_COUNT = "ADD_MULTIPLE_TO_COUNT";
export const REMOVE_FROM_COUNT = "REMOVE_FROM_COUNT";
export const CLEAR_COUNT = "CLEAR_COUNT";
export const UPDATE_COUNT_QUANTITY = "UPDATE_COUNT_QUANTITY";
export const TOGGLE_COUNTT = "TOGGLE_COUNT";

export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";
